openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for optimizer
paths:
    /packs/calculate:
        get:
            tags:
                - optimizer
            summary: calculate optimizer
            description: Calculate optimal pack combinations for a given number of items.
            operationId: optimizer#calculate
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CalculateRequestBody'
                        example:
                            totalItems: 5521850667853442423
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculateOKResponseBody'
                            example:
                                packs:
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                "400":
                    description: Bad Request response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculateOKResponseBody'
                            example:
                                packs:
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                "500":
                    description: Internal Server Error response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CalculateOKResponseBody'
                            example:
                                packs:
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
                                    - quantity: 5272053870220535793
                                      size: 4662976870903077339
    /packs/sizes:
        get:
            tags:
                - optimizer
            summary: getSizes optimizer
            description: Get the current pack sizes.
            operationId: optimizer#getSizes
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetSizesOKResponseBody'
                            example:
                                sizes:
                                    - 474667457818666820
                                    - 1591985036429251049
                                    - 7406854048369655432
                "500":
                    description: Internal Server Error response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetSizesOKResponseBody'
                            example:
                                sizes:
                                    - 3579251599982593480
                                    - 2534687217927780163
                                    - 6955969754630762196
                                    - 3639531370154897817
        put:
            tags:
                - optimizer
            summary: updateSizes optimizer
            description: Update the pack sizes.
            operationId: optimizer#updateSizes
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetSizesOKResponseBody'
                        example:
                            sizes:
                                - 5187262674716634592
                                - 7976492007773777393
                                - 8733443723489356396
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                "500":
                    description: Internal Server Error response.
components:
    schemas:
        CalculateOKResponseBody:
            type: object
            properties:
                packs:
                    type: array
                    items:
                        $ref: '#/components/schemas/Pack'
                    description: Optimal pack combinations (pack size -> quantity)
                    example:
                        - quantity: 5272053870220535793
                          size: 4662976870903077339
                        - quantity: 5272053870220535793
                          size: 4662976870903077339
                        - quantity: 5272053870220535793
                          size: 4662976870903077339
                        - quantity: 5272053870220535793
                          size: 4662976870903077339
            example:
                packs:
                    - quantity: 5272053870220535793
                      size: 4662976870903077339
                    - quantity: 5272053870220535793
                      size: 4662976870903077339
                    - quantity: 5272053870220535793
                      size: 4662976870903077339
            required:
                - packs
        CalculateRequestBody:
            type: object
            properties:
                totalItems:
                    type: integer
                    description: Total number of items to pack
                    example: 1552173628274183304
                    format: int64
            example:
                totalItems: 2993982965767742848
            required:
                - totalItems
        GetSizesOKResponseBody:
            type: object
            properties:
                sizes:
                    type: array
                    items:
                        type: integer
                        example: 6192056192952589381
                        format: int64
                    description: Current pack sizes
                    example:
                        - 8324425566147697766
                        - 8342397683373211688
            example:
                sizes:
                    - 1357076879179761880
                    - 1287891771697475621
            required:
                - sizes
        Pack:
            type: object
            properties:
                quantity:
                    type: integer
                    description: Quantity of this pack size needed
                    example: 1975249710174304874
                    format: int64
                size:
                    type: integer
                    description: Size of the pack
                    example: 9026701606775409556
                    format: int64
            description: Pack represents a pack size and the quantity needed.
            example:
                quantity: 7119139271458250272
                size: 8374315779069350159
            required:
                - size
                - quantity
tags:
    - name: optimizer
      description: The optimizer service calculates optimal pack combinations for a given number of items.
