swagger: "2.0"
info:
    title: Pack Optimizer
    description: Service to calculate optimal pack combinations for a given number of items
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /health:
        get:
            tags:
                - optimizer
            summary: health optimizer
            description: Returns the health status of the service.
            operationId: optimizer#health
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/OptimizerHealthResponseBody'
                        required:
                            - status
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/OptimizerHealthInternalServerErrorResponseBody'
            schemes:
                - http
    /packs/calculate:
        get:
            tags:
                - optimizer
            summary: calculate optimizer
            description: Calculate optimal pack combinations for a given number of items.
            operationId: optimizer#calculate
            parameters:
                - name: quantity
                  in: query
                  description: Total number of items to pack
                  required: true
                  type: integer
                  minimum: 1
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/OptimizerCalculateResponseBody'
                        required:
                            - packs
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/OptimizerCalculateBadRequestResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/OptimizerCalculateInternalServerErrorResponseBody'
            schemes:
                - http
    /packs/sizes:
        get:
            tags:
                - optimizer
            summary: getPackSizes optimizer
            description: Get the current pack sizes.
            operationId: optimizer#getPackSizes
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/OptimizerGetPackSizesResponseBody'
                        required:
                            - sizes
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/OptimizerGetPackSizesInternalServerErrorResponseBody'
            schemes:
                - http
        put:
            tags:
                - optimizer
            summary: updatePackSizes optimizer
            description: Update the pack sizes.
            operationId: optimizer#updatePackSizes
            parameters:
                - name: UpdatePackSizesRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/OptimizerUpdatePackSizesRequestBody'
                    required:
                        - sizes
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/OptimizerUpdatePackSizesBadRequestResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/OptimizerUpdatePackSizesInternalServerErrorResponseBody'
            schemes:
                - http
definitions:
    OptimizerCalculateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: calculate_bad_request_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerCalculateInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: calculate_internal_server_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerCalculateResponseBody:
        title: OptimizerCalculateResponseBody
        type: object
        properties:
            packs:
                type: array
                items:
                    $ref: '#/definitions/Pack'
                description: Optimal pack combinations (pack size -> quantity)
                example:
                    - quantity: 1609558464246327244
                      size: 5614756764895872828
                    - quantity: 1609558464246327244
                      size: 5614756764895872828
                    - quantity: 1609558464246327244
                      size: 5614756764895872828
        example:
            packs:
                - quantity: 1609558464246327244
                  size: 5614756764895872828
                - quantity: 1609558464246327244
                  size: 5614756764895872828
        required:
            - packs
    OptimizerGetPackSizesInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: getPackSizes_internal_server_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerGetPackSizesResponseBody:
        title: OptimizerGetPackSizesResponseBody
        type: object
        properties:
            sizes:
                type: array
                items:
                    type: integer
                    example: 4633574668665543999
                    format: int64
                description: Current pack sizes
                example:
                    - 250
                    - 500
                    - 1000
        example:
            sizes:
                - 250
                - 500
                - 1000
        required:
            - sizes
    OptimizerHealthInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: health_internal_server_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerHealthResponseBody:
        title: OptimizerHealthResponseBody
        type: object
        properties:
            status:
                type: string
                description: Health status of the service
                example: ok
        example:
            status: ok
        required:
            - status
    OptimizerUpdatePackSizesBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: updatePackSizes_bad_request_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerUpdatePackSizesInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: updatePackSizes_internal_server_error_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    OptimizerUpdatePackSizesRequestBody:
        title: OptimizerUpdatePackSizesRequestBody
        type: object
        properties:
            sizes:
                type: array
                items:
                    type: integer
                    example: 6692593150548685321
                    format: int64
                description: New pack sizes to update
                example:
                    - 250
                    - 500
                    - 1000
        example:
            sizes:
                - 250
                - 500
                - 1000
        required:
            - sizes
    Pack:
        title: Pack
        type: object
        properties:
            quantity:
                type: integer
                description: Quantity of this pack size needed
                example: 1330956490353766758
                format: int64
            size:
                type: integer
                description: Size of the pack
                example: 669619572349922072
                format: int64
        description: Pack represents a pack size and the quantity needed.
        example:
            quantity: 2594967611078269106
            size: 354376545860708946
        required:
            - size
            - quantity
